from behave import *


@given("we have behave installed")
def step_impl(context):
    pass


@when("we implement a test")
def step_impl(context):
    assert True is not False


@then('behave will test it all')
def step_then(context):
    pass
    # This was autogenerated using cucumber syntax.
    # Please convert to use regular expressions, as Behave does not currently support Cucumber Expressions